OPEN SCHEMA tpc;

-- KEYs     DEC(11)
-- INTEGERs DEC(10)
-- DECIMALs DEC(12,2)

CREATE OR REPLACE TABLE HISTORY2( H_P_KEY DEC(11), H_S_KEY DEC(11), H_O_KEY DEC(11), H_L_KEY DEC(10), H_DELTA DEC(10), H_DATE_T TIMESTAMP );

COMMIT;
exit;
